# Generated by Django 3.1.4 on 2021-01-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no-name.jpg', upload_to='profile'),
        ),
    ]
