# Generated by Django 3.1.4 on 2021-01-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
