# Generated by Django 3.1.4 on 2021-01-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0003_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no-name.jpg', null=True, upload_to='profile'),
        ),
    ]
